### PR TITLE
Feature/migrate html minifier terser

### PR DESCRIPTION
**Pull request by multivoltage**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### Goal
I saw an issue of an user that ask support for **html-minifier-terser in place of html-minifier.**
Only thing that change is that minify method is a promise.

### Behavior using old html-minifier
Since in js we can do
```js
function syncMethod(){
   return "hello";
}
const output = await syncMethod()
```
Even point-of-view will add the terser version which is Promise based, configuring options like this:
```js
const minifier = require('html-minifier')
// optionally defined the html-minifier options
const minifierOpts = {
  removeComments: true,
}
  options: {
    useHtmlMinifier: minifier,
    htmlMinifierOptions: minifierOpts
  }
```

can be done also using **html-minifier** instead **html-minifier-terser**

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm terrified of mixing callbacks and promises in this way. In my experience, it is the recipe for:

1. performance issues
2. memory leaks
3. race conditions

I'm ok with moving the whole codebase to an async/await or just adding a `.then()` to the calls to the minifier. However the best approach would be to drop the callbacks and use async/await everywhere.

**Comment by multivoltage** [comment]
In my small experience I prefer only await and async instead callback. But there are some case where we cannot wait a "line" but only start a "parallel" method. 
I will do an analysis next day.

If we agree to replace all callback with await async, do you you think I can put changes in that pr ?

**Comment by mcollina** [comment]
It's better to do the two things separately

**Comment by multivoltage** [comment]
Ok. I will try to use callback for this or. Thanks

**Comment by multivoltage** [comment]
@mcollina when you say to migrate all codebase to async await you are considering also for example readFile() or only calls "then()" for promises?

**Comment by mcollina** [comment]
All of it, yes.

**Comment by multivoltage** [comment]
I resume this PR since async flow was introduced

**Comment by mcollina** [comment]
CLosing for no activity

**Comment by multivoltage** [comment]
OK.
I updated PR (like I said in the previous comment).
Did you expect other changes?

**Review by gurgunday — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
