### PR TITLE
feat: support liquidjs (#172)

### PR DESCRIPTION
**Pull request by alemagio**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by alemagio** [comment]
`
const fastify = require('fastify')()
const { Liquid } = require('liquidjs')
const path = require('path')

const engine = new Liquid({
  root: path.join(__dirname, 'templates'),
  extname: '.liquid'
})

engine.registerTag('header', {
  parse: function (token) {
    const [key, val] = token.args.split(':')
    this[key] = val
  },
  render: async function (scope, emitter) {
    const title = await this.liquid.evalValue(this.content, scope)
    emitter.write(`<h1>${title}</h1>`)
  }
})

fastify.register(require('./index'), {
  engine: {
    liquid: engine
  }
})

fastify.get('/', (req, reply) => {
  reply.view('/templates/index.liquid', { todos: ['fork and clone', 'make it better', 'make a pull request'] })
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
`

This is an example

**Comment by StarpTech** [comment]
Hi @alemagio, please add a test.

**Comment by alemagio** [comment]
Sure

**Comment by alemagio** [comment]
I added tests and a small paragraph to the doc.

**Comment by alemagio** [comment]
Any idea about CI failure?
I tried locally using both node 12 and 14 and it works.

**Comment by alemagio** [comment]
Just noticed I did not add the row for supported engines on README

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
