### PR TITLE
chore tap 15

### PR DESCRIPTION
**Pull request by Eomm**
This is an automatic PR created with [massive-wax](https://github.com/Eomm/massive-wax)!

### CODE REVIEW

**Comment by mcollina** [comment]
In order to fix the tests, you should re-run them with `TAP_SNAPSHOT=1 npm test`.

**Comment by mcollina** [comment]
you might want to remove `tap-snapshots` folder before doing so.

**Comment by Eomm** [comment]
Yes, I did it locally, but it generates a new files tree. I must check how it works

**Review by mcollina — APPROVED** [review]
lgtm

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
