### PR TITLE
Added extension support for handlebars engine.

### PR DESCRIPTION
**Pull request by leomleao**

### CODE REVIEW

**Comment by cemremengu** [comment]
Thanks! Could you please add a unit test?

**Comment by leomleao** [comment]
Dang. Code worked here cuz engine was being instanced with hbs instead of handlebars here. I see a error now, problem with handlebars is that it could be saved with multiple extensions. One could suggest to change the option includeViewExtension to a string|array where you could select possible extensions, but I will just rename my templates to *.handlebars for now :)

**Comment by leomleao** [comment]
I realized even *.handlebars was not being recognized. I changed the handlebars view to make it similar to the rest. With an unit test as well.

**Comment by mcollina** [comment]
Linting is failing: https://travis-ci.org/fastify/point-of-view/jobs/479691292#L475.

**Comment by leomleao** [comment]
Oops, my bad.

**Comment by mcollina** [comment]
@leomleao I think I messed up this PR while resolving the conflict. Would you mind to revert my latest change and rebase everything on top of master? I'm  sorry for this, this PR got stranded in my backlog for too long.

**Comment by leomleao** [comment]
There is only one change [here](https://github.com/fastify/point-of-view/blob/master/index.js#L272):
`page = getPage(page, 'hbs')`

which should be this:
`page = getPage(page, type)`

**Pull request closed without merging**
