### PR TITLE
chore: add benchmark PR workflow

### PR DESCRIPTION
**Pull request by mweberxyz**
Adds the shared `plugins-benchmark-pr.yml` workflow to PRs.

### Usage
Add the `benchmark` tag to a PR in order to run benchmarks and compare against `master`.

### Example
https://github.com/mweberxyz/point-of-view/pull/2

#### Checklist
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mweberxyz** [comment]
Changing to draft state - I would like to make a few changes to make the output more useful to what is requested in a typical PR conversation.

**Comment by Uzlopak** [comment]
@mweberxyz 
There is a bug in the benchmark flow.

can you take care of it please?

https://github.com/fastify/workflows/issues/93

**Comment by mweberxyz** [comment]
Leaving this draft for a little bit longer to see if there's any feedback on https://github.com/fastify/workflows/issues/121, otherwise will return and go forward as is.

**Comment by mweberxyz** [comment]
Turns out automating statistically significant, actionable benchmarks are easier said than done. Still spending time poking, but closing for now.

**Pull request closed without merging**
