### PR TITLE
Append view extension in reply.view

### PR DESCRIPTION
**Pull request by shkumbin**
Specifying view extension in `reply.view` is not necessary if we decide to merge this PR. This is just a proposal.

### CODE REVIEW

**Comment by delvedor** [comment]
I'm neutral to this, @mcollina thoughts?

**Comment by mcollina** [comment]
Can you make this optional?

**Comment by shkumbin** [comment]
@delvedor @mcollina I added `includeViewExtension` property, so that it can be optional.

**Comment by shkumbin** [comment]
I think it looks okay now @mcollina.

**Pull request merged**
