### PR TITLE
feat: add support for eta@3.x

### PR DESCRIPTION
**Pull request by multivoltage**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

#### Goal
I want etajs@3.x support for this project. Hope my PR or other people want same feature

#### What I did not
Not edited documentation since probably I cannot say to be skilled enough in this project

#### What I did
I tried to make all the tests work by changing as few things as possible. Unfortunately, one big change involves creating an Eta instance with new Eta().
I had to change many parts of the tests. Not sure about many changes. Finally I started a test project by installing fastify, and linking index.js. I managed to get the basic example working:
```js
import view from '../point-of-view-new'
import { Eta } from 'eta'

const eta = new Eta()

const fastify = Fastify({
    logger: true
  })
  
fastify.register(view, {
    engine: {
      eta
    },
});

  
// Declare a route
fastify.get('/', function (request, reply) {
    reply.view("/templates/hello.eta", { name: "diego" });
})
```

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by multivoltage** [comment]
@mcollina 
maybe I should have created a special issue for this change?

**Comment by mcollina** [comment]
why?

**Comment by multivoltage** [comment]
Honestly I don't know. Is my second time I submit a pr ;)

**Comment by Eomm** [comment]
Please open a new detailed issue adding a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

**Pull request merged**
