### PR TITLE
issue29, set default mime type to 'text/html; charset=utf-8'

### PR DESCRIPTION
**Pull request by smartiniOnGitHub**
and update dependencies and docs.
All should be done.
Tell me if there is something to improve or change.

Thanks,
Sandro

### CODE REVIEW

**Comment by mcollina** [comment]
@delvedor is this ok for you?

**Comment by mcollina** [comment]
This does not land cleanly anymore. Can you rebase?

**Comment by smartiniOnGitHub** [comment]
Hi all and thanks for feedback ... I'll rebase on top of the updated master as soon as possible.
@delvedor To change default charset, should be possible inside the string for the mimetype, like 'text/html; charset=utf-8' ... should be good, right ?

**Comment by delvedor** [comment]
@smartiniOnGitHub no, I mean that at the moment you are overwriting the charset in every case.
I think that a solution can be a custom option and then inside chain it:
```js
opts.charset = opts.charset || 'utf-8'
//...
this.header('Content-Type', 'text/html; charset=' + charset).send(html)
```

**Comment by smartiniOnGitHub** [comment]
@delvedor ok, I need to find if there is a default opts object and add that default and override ...

But I have too much conflicts now, so for now I prefer to destroy the branch (and so this PR) and re-create from updated master (and a new PR will follow), sorry for the noise.

**Pull request closed without merging**
