### PR TITLE
Add support of includeViewExtension with Handlebars extension ".hbs"

### PR DESCRIPTION
**Pull request by Flewerty**

### CODE REVIEW

**Comment by smartiniOnGitHub** [comment]
LGTM

**Comment by mcollina** [comment]
Can you please add a unit test?

**Comment by smartiniOnGitHub** [comment]
@Flewerty @mcollina can I help by adding some simple test on this ?

**Comment by Flewerty** [comment]
> 
> 
> @Flewerty @mcollina can I help by adding some simple test on this ?

Of course you can, thanx

**Comment by smartiniOnGitHub** [comment]
PR opened into Flewerty fork of point-of-view ... let's see after the merge (or the rewrite) of my changes.

**Comment by Flewerty** [comment]
Thanx to @smartiniOnGitHub for Unit test

**Comment by smartiniOnGitHub** [comment]
@mcollina time to merge ? :-) Thanks. Bye

**Comment by smartiniOnGitHub** [comment]
@mcollina thanks a lot.

**Pull request merged**
