### PR TITLE
Add support for Handlebars compile options and data variables

### PR DESCRIPTION
**Pull request by mohd-akram**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
Can we have some typings?

**Comment by mohd-akram** [comment]
@Uzlopak Where?

**Review by gurgunday — APPROVED** [review]
implementation lgtm

`useDataVariables` sounds a little vague but the README clearly explains what it does

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
