### PR TITLE
chore(.prettierignore): add

### PR DESCRIPTION
**Pull request by mweberxyz**
Add .prettierignore to avoid making a mess

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — CHANGES_REQUESTED** [review]
We dont use prettier?!

**Comment by mweberxyz** [comment]
See https://github.com/fastify/fastify/pull/2269 and particularly https://github.com/fastify/fastify/pull/2269#issuecomment-773981605

prettier makes a mess of this repo when enabled, and both core and other plugins have this file for consistency

**Comment by Uzlopak** [comment]
Usually we do such changes centralized in the skeleton repo. Master of the Order is @Fdawgs 

Please open a corresponding PR in https://github.com/fastify/skeleton

**Comment by mweberxyz** [comment]
https://github.com/fastify/skeleton/pull/53 created and this PR updated to be the exact change suggested there.

**Comment by Uzlopak** [comment]
I saw that. Just be a little bit patient. We are compared to other teams relatively fast. Expect that we decide this through in about a week.

**Comment by mweberxyz** [comment]
No rush! Just adding the link here in for context.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
Please also add the change in the eslintrc file as you did in skeleton

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
