### PR TITLE
added view eval to check for content-type before assigning a default

### PR DESCRIPTION
**Pull request by DarthGoon**
note: 

line 54: while i was inspecting, the content-type prop was all lower-case.  That's why this is all lower-case, opposed to "Content-Type".

### CODE REVIEW

**Comment by DarthGoon** [comment]
should i also bump the patch version in the package.json?
`0.2.1`?

**Comment by delvedor** [comment]
@DarthGoon regarding the `package.json` don't worry, I'll do it before the release :)

**Comment by DarthGoon** [comment]
duplicated a test for this specific use case (preserving xml content type).  let me know if i should do it differently

**Comment by delvedor** [comment]
Released in [v0.2.1](https://github.com/fastify/point-of-view/releases/tag/v0.2.1), thanks for contributing!

**Pull request merged**
