### PR TITLE
Partials support for Handlebars engine

### PR DESCRIPTION
**Pull request by amer8**
Should support Handlebars Partials

http://handlebarsjs.com/#partials

### CODE REVIEW

**Comment by amer8** [comment]
@mcollina Object.entries is not a function on Node 6.x. Should we drop support for 6.x or rewrite?

**Comment by mcollina** [comment]
Please keep support for Node 6. Object.keys is there and works well.

**Comment by mcollina** [comment]
I'm sorry, would you mind rebasing after #122 landed?

**Comment by amer8** [comment]
Done.

**Pull request merged**
