### PR TITLE
Support load template from memory for marko template engine

### PR DESCRIPTION
**Pull request by lanyusan**
Marko template engine's loader supports loading template from memory, which is important for the use case of pre-loading template from central repository like AWS, edited through web editor.

This pull request supports this use case by testing if `templateSrc` exists in `opts` and pass it to `marko` loader if it exists.
Developer using this model should pass pre-loaded template source as `templateSrc` property of `opts`.

The `path` for template page should still be provided and the folder should still exist or be created for marko loader's search of components. It has been tested with the sample `fastify` integration code of `marko`.

`npm run test` result:

```
Suites:   13 passed, 13 of 13 completed
Asserts:  1027 passed, of 1027
Time:     4s
```
File               |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
-------------------|----------|----------|----------|----------|-------------------|
All files          |    81.74 |    75.61 |    90.91 |    83.54 |                   |
 point-of-view     |    82.97 |    78.26 |    95.92 |    83.44 |                   |
  index.js         |    82.97 |    78.26 |    95.92 |    83.44 |... 59,560,562,578 |
 point-of-view/out |    58.82 |     37.5 |       50 |     87.5 |                   |
  testjst.js       |    58.82 |     37.5 |       50 |     87.5 |                 8 |

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Comment by lanyusan** [comment]
Yes I have added a unit test and the test has passed.

```
test('fastify.view to load template from memory with marko engine', t => {
  t.plan(6)
  const fastify = Fastify()
  const marko = require('marko')
  const data = { text: 'marko' }
  const templateSrc = `
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    <p>\${data.text}</p>
  </body>
</html>
`

  const opts = { templateSrc }

  fastify.register(require('../index'), {
    engine: {
      marko: marko
    }
  })

  fastify.ready(err => {
    t.error(err)

    fastify.view('templates/index.marko', data, opts, (err, compiled) => {
      t.error(err)
      const markoLoaded = marko.load('./templates/index.marko', opts).renderToString(data)

      t.strictEqual(markoLoaded, compiled)
      fastify.ready(err => {
        t.error(err)

        fastify.view('templates/index.marko', data, (err, compiled) => {
          t.error(err)
          const markoLoaded = marko.load('./templates/index.marko', opts).renderToString(data)
          t.strictEqual(markoLoaded, compiled)
          fastify.close()
        })
      })
    })
  })
})

```

**Comment by lanyusan** [comment]
@mcollina 

Hi will you look at my submission? I am working on a project and would need this pull request merged. And if you decide not to, I would like to hear it sooner so I can take a different path. 

Thanks.

**Review by jsumners — COMMENTED** [review]
It looks like this module is missing documentation on all options, so I can't request that be updated. But I think a good compromise would be to add a new example script in the same style as https://github.com/fastify/point-of-view/blob/9899c0d25128edf909351d00d6d08875ccc9152c/example-ejs-with-some-options.js

**Comment by lanyusan** [comment]
@jsumners 
I have added a marko example. As I am not the original marko module developer, I only added some comments for the part that concerns me, passing pre-loaded `templateSrc` from any source as a property of `opts` for marko to load in memory as opposite to loading from file system.

```
'use strict'

const fastify = require('fastify')()
const resolve = require('path').resolve
const templatesFolder = 'templates'
const marko = require('marko')

const data = { text: 'marko' }

const templateSrc = `
<!DOCTYPE html>
<html lang="en">
  <head></head>
  <body>
    <p>\${data.text} from memory</p>
  </body>
</html>
`

// To ask marko compile template from pre-loaded template for example from a web editor
// Pass the template as property templateSrc of opts
// The page parameter still should be passed and its path should exist in so that marko engine
// could lookup components along the parent path.

const opts = { templateSrc }

fastify.register(require('./index'), {
  engine: {
    marko
  },
  includeViewExtension: true,
  templates: templatesFolder,
  options: {
    filename: resolve(templatesFolder)
  },
  charset: 'utf-8' // sample usage, but specifying the same value already used as default
})

// Load template from memory
// Web page should show text: marko from memory

fastify.get('/mem', (req, reply) => {
  reply.view('mem', data, opts)
})

// Load template from file system
// Web page should show text: marko

fastify.get('/file', (req, reply) => {
  reply.view('index', data)
})

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})

```

**Review by mcollina — APPROVED** [review]
lgtm

**Review by lilpoozie2005 — APPROVED** [review]

**Pull request merged**
